### ISSUE TITLE
这个项目要替换cnpm.org吗？

### ISSUE THREAD

**Issue by lubezhang** [cnpm/registry#1]
cnpmjs.org项目是否继续维护？ registry是否替换cnpmjs.org项目？

**Comment by JacksonTian** [comment]
Just rewrite with egg.js.

**Comment by fengmk2** [comment]
两个都会维护，这个项目重构完成后会将cnpmjs.org一拆为二：web 和 registry。web 会完全基于 registry 接口实现。

**Comment by footearth** [comment]
现在能跑吗？

**Comment by fengmk2** [comment]
才刚刚开始启动 https://github.com/cnpm/registry.cnpmjs.org/issues
